name: newspulse
description: AI Powered Bengali News Shorts Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_core: ^4.8.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.4.0
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3

  # STATE MANAGEMENT
  flutter_riverpod: ^3.0.3

  # ROUTING
  go_router: ^16.2.0

  # UI
  google_fonts: ^6.3.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0

  # VIDEO
  video_player: ^2.10.0
  chewie: ^1.12.1
  cached_video_player_plus: ^4.0.4

  # IMAGE
  cached_network_image: ^3.4.1

  # NETWORK
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  # LOCAL STORAGE
  shared_preferences: ^2.5.3

  # NOTIFICATIONS
  flutter_local_notifications: ^19.4.0

  # PERMISSIONS
  permission_handler: ^12.0.1

  # ANIMATIONS
  animations: ^2.0.11

  # UTILITIES
  intl: ^0.20.2
  uuid: ^4.5.1

  # SVG
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/